---
- name: Install Nginx Web Server on CentOS
  hosts: all
  become: yes
  tasks:
    - name: Update the package cache
      become: yes
      apt:
        update_cache: yes

    - name: Install Nginx
      yum:
        name: nginx
        state: present
    
    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes



